# Generated by Django 2.1 on 2020-01-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190730_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
