# Generated by Django 3.1 on 2020-10-28 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_project', models.CharField(default='None', max_length=20, verbose_name='From Project')),
                ('issue_status', models.CharField(default='Unconfirmed', max_length=20, verbose_name='Status')),
                ('issue_severity', models.CharField(choices=[('LO', 'Low'), ('ME', 'Medium'), ('HI', 'High'), ('CR', 'Critical')], default='LO', max_length=2, verbose_name='Severity')),
                ('issue_title', models.CharField(max_length=40, verbose_name='Title')),
                ('issue_description', models.TextField(verbose_name='Description')),
                ('issue_env', models.TextField(blank=True, null=True, verbose_name='Environnement*')),
                ('issue_url', models.URLField(blank=True, null=True, verbose_name='URL*')),
                ('issue_expected', models.TextField(verbose_name='What was expected ?')),
                ('issue_steps', models.TextField(verbose_name='Steps to reproduce')),
                ('issue_created', models.DateField(auto_now_add=True)),
                ('issue_last_modified', models.DateField(auto_now=True)),
                ('issue_proof', models.FileField(blank=True, null=True, upload_to='', verbose_name='Visual Proof*')),
                ('issue_extra', models.TextField(blank=True, null=True, verbose_name='Extra Informations*')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='None', max_length=20, unique=True, verbose_name='Project Name')),
                ('project_created', models.DateField(auto_now_add=True)),
                ('project_description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('project_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Project Admin')),
            ],
        ),
    ]
