# Generated by Django 3.0.3 on 2020-02-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=50)),
                ('issue_description', models.TextField()),
                ('issue_status', models.CharField(max_length=20)),
                ('issue_env', models.TextField()),
                ('issue_url', models.TextField()),
                ('issue_proof', models.FileField(upload_to='')),
                ('issue_steps', models.TextField()),
                ('issue_expected', models.TextField()),
                ('issue_extra', models.TextField()),
                ('issue_severity', models.CharField(max_length=10)),
            ],
        ),
    ]
