# Generated by Django 3.1 on 2020-10-29 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_author',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_project_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bugtracker.project', to_field='project_name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL, verbose_name='Project Admin'),
        ),
    ]
