# Generated by Django 3.1 on 2020-08-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issued_last_modified',
            new_name='issue_last_modified',
        ),
    ]
