# Generated by Django 3.0.3 on 2020-02-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_project',
            field=models.CharField(default='None', max_length=20, verbose_name='From Project'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_env',
            field=models.TextField(blank=True, null=True, verbose_name='Environnement*'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_expected',
            field=models.TextField(verbose_name='What was expected ?'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_extra',
            field=models.TextField(blank=True, null=True, verbose_name='Extra Informations*'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_proof',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Visual Proof*'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_severity',
            field=models.CharField(choices=[('LO', 'Low'), ('ME', 'Medium'), ('HI', 'High'), ('CR', 'Critical')], default='LO', max_length=2, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_status',
            field=models.CharField(max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_steps',
            field=models.TextField(verbose_name='Steps to reproduce'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_url',
            field=models.TextField(blank=True, null=True, verbose_name='URL*'),
        ),
    ]
