# Generated by Django 3.1 on 2020-10-29 09:17
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def forward_func(apps, schema_editor):
    Issue = apps.get_model('bugtracker', 'Issue')
    Project = apps.get_model('bugtracker', 'Project')
    for issue in Issue.objects.all():
        issue.issue_project_link, created = Project.objects.get_or_create(project_name='Bugtracker')
        issue.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtracker', '0002_auto_20201029_1013'),
    ]

    operations = [
        migrations.RunPython(forward_func),
    ]
