# Generated by Django 3.1 on 2020-10-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0003_populatefk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='issue_project',
        ),
    ]
