# Generated by Django 3.1 on 2020-10-29 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0004_remove_issue_issue_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_project_link',
            new_name='issue_project',
        ),
    ]
