# Generated by Django 3.1 on 2020-10-29 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugtracker', '0005_auto_20201029_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_devs',
            field=models.ManyToManyField(db_table='whodevswhat', related_name='devs', to=settings.AUTH_USER_MODEL),
        ),
    ]
