# Generated by Django 3.1 on 2020-08-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0006_auto_20200829_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
